geektime:
#  cache: guava
  school:
    class1:
      students:
        - id: 1
          name: Java
        - id: 2
          name: go
    student100:
      id: 10
      name: cpp
  klass:
    students:
      - id: 3
        name: Python
  student:
    id: 4
    name: Ruby
spring:
  redis:
    host: localhost
    port: 6379
